Added Bangladesh Inter university Nationals Debate Format
czlee/debatekeeper-formats pull request #37
Opened 2024-04-08 07:43 UTC by Taraldinn

This debate format is popular and main stream debate format in Bangladesh. 
It is Three VS Three 
5 Minutes of Speech
3 minutes Replies

2024-04-10 09:39 UTC, czlee requested changes
Hi @Taraldinn, thanks for submitting this! It'd be great to have it in the repository. I'm requesting a few changes to align with stylistic guidelines.

If you haven't already, please have a look at our contributing guidelines: https://github.com/czlee/debatekeeper-formats/blob/main/.github/CONTRIBUTING.md

2024-04-10 09:39 UTC, czlee commented on v1/formats.json
No need to update this file—I have GitHub workflows to do this automatically, which is preferable because it copies information from the XML file 😊 Would you please remove it from the PR?

2024-04-10 09:39 UTC, czlee commented on v1/formats/BDIV.xml
The file name needs to be lower case, so `bdiv.xml`.

2024-04-10 09:39 UTC, czlee commented on v1/formats/BDIV.xml
> +    <used-at>National IV</used-at>
```suggestion
    <used-at>Bangladesh National Intervarsity</used-at>
```
(prefer no abbreviations and specify country if it's part of the tournament name, please modify if the official tournament name is different)

2024-04-10 09:39 UTC, czlee commented on v1/formats/BDIV.xml
> +
please remove this blank line

2024-04-10 09:39 UTC, czlee commented on v1/formats/BDIV.xml
> +  <version>1.00</version>
```suggestion
  <version>1</version>
```
version numbers are integers here

2024-04-12 13:19 UTC, Taraldinn commented on v1/formats.json
sorry for late review . I was busy with something ? Will I remove this PR right now ?

2024-04-12 13:34 UTC, closed without merging

2024-04-13 10:05 UTC, czlee commented on v1/formats.json
@Taraldinn You don't owe an apology for attending to something here three days later! Absolutely no deadlines in this repository, I'd be in such a glass house if I tried to imply any. It's just a spare-time project 😀